apiVersion: v1
kind: Service
metadata:
  name: websocket-chat-server
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: websocket-chat-server
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
